version: '3.8'
services:
  backend:
    build: .
    ports:
      - "5000:3000"
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydb
      - NODE_ENV=production
      - PORT=3000
  frontend:
    build: ./frontend
    ports:
      - "80:80"
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
